name: Build Windows EXE

on:
  push:
    branches:
      - main  # или используйте вашу основную ветку, если это не main

jobs:
  build:
    runs-on: windows-latest  # Выбираем Windows для упаковки .exe

    steps:
      # Шаг 1: Получаем код из репозитория
      - name: Checkout code
        uses: actions/checkout@v2

      # Шаг 2: Настроим Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Укажите свою версию Python

      # Шаг 3: Устанавливаем зависимости (если у вас есть requirements.txt)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Убедитесь, что у вас есть файл requirements.txt с зависимостями, если нужно

      # Шаг 4: Устанавливаем PyInstaller
      - name: Install PyInstaller
        run: pip install pyinstaller

      # Шаг 5: Строим .exe файл с помощью PyInstaller
      - name: Build EXE with PyInstaller
        run: pyinstaller --onefile --windowed main.py  # Замените "main.py" на имя вашего главного файла

      # Шаг 6: Сохраняем .exe файл как артефакт, чтобы его можно было скачать
      - name: Upload EXE as artifact
        uses: actions/upload-artifact@v2
        with:
          name: 2D-Arcade-Game-exe
          path: dist/2D-Arcade-Game.exe

