name: Build Windows EXE

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install PyInstaller
        run: pip install pyinstaller

      - name: Build EXE with PyInstaller
        run: pyinstaller --onefile --windowed main.py

      - name: Upload EXE as artifact
        uses: actions/upload-artifact@v2
        with:
          name: game-exe
          path: dist/game.exe 
