name: Build EXE

on:
  push:
    paths:
      - '**.py'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Загрузка репозитория
      uses: actions/checkout@v3

    - name: Установка Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Установка зависимостей
      run: |
        python -m pip install --upgrade pip
        pip install pygame pyinstaller

    - name: Сборка .exe файла
      run: |
        pyinstaller --onefile --windowed main.py

    - name: Загрузка .exe в релиз
      uses: actions/upload-artifact@v3
      with:
        name: GameExecutable
        path: dist/*.exe
